module api {
    typedef octet byteArray[4*1024];
    interface DataNode {
        byteArray read(in long block_id);
        void append(in long block_id, in byteArray bytes);
        long randomBlockId();
    };
    interface NameNode{
        string open(in string filepath,in long mode);
        void close(in string fd);
        void registerDataNode(in long dataNodeId, in string s);
        void registerBlock(in long oldBlockId, in long newBlockId);
        string updateFile(in string filepath);
    //TODO: complete the interface design
    };
};
